### ISSUE TITLE
user vim :term instead of standalone terminal window?

### ISSUE THREAD

**Issue by hems** [supercollider/scvim#37] opened 2017-11-15 03:13 UTC
if `echo has('terminal')` returns `1` then the current vim build will have the `:term` command which i believe behaves pretty much like neovim :term

We should then be able to open SC in a split on vim instead of using a standalone terminal?

**Comment by gusano** [comment] 2017-12-06 10:05
@hems with #38 we add support for `screen` and `tmux`.
Going to close this. Feel free to reopen if you really think that we should also support `vim :term` but meanwhile using `screen` or `tmux` sounds like an acceptable (if not better) workaround :)

**Comment by hems** [comment] 2017-12-06 11:38
I think having it on vim :term is much more awesome as the output from the terminal becomes a buffer not to say you remove the tmux and screen dependency, some people ( including me ) use alternative software!

anyway, thanks for sharing the work!

**Comment by gusano** [comment] 2017-12-06 11:51
@hems Reopening then :)
No idea when this will be done though..

**Comment by hems** [comment] 2017-12-06 12:38
nice one, awesome! i wish i was more useful and able to help but all i can do is copy and paste stuff on my vimrc :(

**Comment by dvzrv** [comment] 2017-12-07 09:16
Hmm, it also depends on how well it performs within vim.
I think it would be probably wise to

- fix screen/tmux support as intended
- additionally incorporate :term support
- make it user-settable (.vimrc) to choose whether to use tmux/screen (if running vim in either of them) or :term and default to :term, if running gvim/vim in neither of the multiplexers

Does that sound reasonable?

**Comment by claudiocabral** [comment] 2019-10-03 14:31
I'd like to give a shot at adding this feature, I can start working on it next week

**Comment by claudiocabral** [comment] 2019-10-04 07:50
So, had some time this morning and got it up and running here. Would love to have some other people test it :)

**Comment by capocasa** [comment] 2019-11-07 22:39
Working out some kinks but @claudiocabral's stuff in the PR is great.

**Comment by claudiocabral** [comment] 2019-12-03 08:28
@capocasa we can close this one now ;)

**Comment by capocasa** [comment] 2019-12-03 10:09
Oh I thought merge closes it!

**Closed by capocasa** 2019-12-03 10:09 UTC
Labels: enhancement, help wanted
