### ISSUE TITLE
sclangpipe_app can't find sclang if aliased

### ISSUE THREAD

**Issue by blacksound** [supercollider/scvim#2] opened 2016-05-01 18:47 UTC
I'm on OS X 10.11
If 'sclang' is aliased, sclangpipe_app can't detect it. 
`which sclang`.chmod which returns an empty string if sclang is aliased.
If one shouldn't use alias for this maybe the used should be warned?

**Comment by dvzrv** [comment] 2016-05-03 12:07
I can confirm this. I have the same issue on Linux atm.
Which is kind of awkward... because I know it used to work oO

**Comment by blacksound** [comment] 2016-05-03 13:34
If I remember correclty it used to work on my behalf also but I don't know what changed.
From I have understood, the 'which' command is not really recommended for this purpose.
I've tested with other commands, such as 'command' and 'type' but no luck with those either.

Maybe we should look into the whole structure of detecting the 'sclang' and 'scsynth' paths?

One idea would be to be able to define the paths in the .scvimrc file and have 'sclangpipe_app' check if those are defined. If not defined, the script should try to find the paths automatically.

**Comment by dvzrv** [comment] 2016-05-03 14:16
Yes.
My idea after doing the [additions for tmux and screen](https://github.com/supercollider/supercollider/pull/990) was to rewrite the sclang_app in bash or something similar anyways.
Not sure if this can be done easily, but it would be system-independent.
I'd like to not use ruby for it but go into a general python direction, maybe even further adhering to the standards introduced with neovim.

Fleshing out the way the plugin looks for the paths is surely a good idea.
I think scvim is also still using (now) deprecated methods from Platform (like helpDir).

**Comment by blacksound** [comment] 2016-05-04 06:37
Another idea is making only one default location, i.e. OS X '/Application/SuperCollider..' and linux '/usr/local/share/SuperCollider..', which could be overridden by the .scvimrc file.
I'd prefer that instead of having the script look into many different folders, not really knowing which version is being run.

**Comment by crucialfelix** [comment] 2016-06-14 07:19
It's more than just the aliasing. (even if you mean symlink)

Qt linking requires that you run it from the directory where the original is. You can use a shell script that execs sclang and passes the arguments through. That's what I've done in the past. That only really works for scsynth though; Qt linking is still a problem and the app will not run.

**Comment by capocasa** [comment] 2019-11-07 21:32
Cleaning up ancient issues!

When using a bash `alias sclang=sclang -g 512k` that's not normally something you can expect a unix system to pick up outside of your shell. We could warn, but the behavior is actually standard behavior for a *nix system, so I would suggest to just close this since it's more about unix than supercollider.

The best way I found to add parameters by default was, indeed, to create small shell scripts. I usually put them in both ~/bin/sclang and ~/bin/scsynth, worked fine.

    #!/bin/bash
    exec /usr/bin/sclang -g 512k $@

    #!/bin/bash
    exec /usr/bin/scsynth -w8196 $@

Sucker as I am for over-engineering, here's a generic script that will pick out the next command up the path with the same name as the file, so you can copy paste the line instead of having to type /usr/bin/sclang by hand (the horror).

    #!/bin/bash
    CMD=$(which -a $(basename $0)  | head -2 | tail -1)
    exec $CMD -g 512k $@

**Closed** 2019-11-07 22:40 UTC
Labels: bug, sc-related
