### ISSUE TITLE
HelpBrowser doesn't automatically render Help pages

### ISSUE THREAD

**Issue by dvzrv** [supercollider/scvim#33] opened 2017-04-29 17:43 UTC
When launching the HelpBrowser on a keyword through vim (ctrl+K), the HelpBrowser renders the HTML Help page for the keyword using SCDoc and opens it (`HelpBrowser.openHelpFor("keyword");`).
Inside the HelpBrowser however, this doesn't apply and thus clicking on links for keywords, that have not been rendered yet, does nothing.
Is there any way to change this? It's pretty annoying to use the HelpBrowser this way.
SCIDE does this on the fly. I wonder, in what way this can be changed when using scvim, as the HelpBrowser is launched as a singleton.

On a different note: It would be great to have the HelpBrowser stay open even between recompiles, or re-open the last opened Help page on recompile. Currently it is closed, as the sclang process launching it is killed.

**Comment by capocasa** [comment] 2019-11-07 23:06
Yeah that would be cool.

This sounds a little out-of-scope though- I wouldn't know how to fix the help browser from within scvim, because it's just a rather thin wrapper for sclang. So I'm passing the buck to sclang on this one- please reproduce when opening a help file directly from sclang and report there.

According to community enthusiasm (as perceived by me) scvim community would prefer to focus on fixing help browser related problems by switching to vim native help. Therefore, considering this a duplicate of #46.

**Closed by capocasa** 2019-11-07 23:06 UTC
Labels: bug, sc-related
